### ISSUE TITLE
Markdown to HTML Converter 

### ISSUE THREAD

**Issue by divyanshu887** [MiHarsh/Basic-Projects#2]
i want to add a script of markdown to html converter

**Comment by MiHarsh** [comment]
Can you give me some gist regarding this ?

**Comment by divyanshu887** [comment]
# Description
This Script would convert markdown files into HTML. Can be extremely useful for developers who are implementing modern text enhancement features as most blog sites, note apps etc. are adapting markdown support.

### Language
-  Javascript
## Details on the Script
name | about  |
-- | --  |
Markdown to HTML converter | Easily convert Markdown to HTML by use of available parsing libraries |

**Comment by MiHarsh** [comment]
Looks Good !!
